# this file is used for configuration of DigitalOcean
# for integration tests in the CI
---
driver:
  name: digitalocean
  size: s-1vcpu-1gb
  region: nyc3

transport:
  ssh_key: '~/.ssh/ci_id_rsa'
  max_wait_until_ready: 30

platforms:
- name: ubuntu-14-04
  driver_config:
    image: ubuntu-14-04-x64
- name: ubuntu-16-04
  driver_config:
    image: ubuntu-16-04-x64
- name: centos-6
  driver_config:
    image: centos-6-x64
- name: centos-7
  driver_config:
    image: centos-7-x64
- name: debian-7
  driver_config:
    image: debian-7-x64
- name: debian-8
  driver_config:
    image: debian-8-x64
- name: fedora-26
  driver_config:
    image: fedora-26-x64
- name: fedora-27
  driver_config:
    image: fedora-27-x64
