# this file is used for configuration of kitchen dokken
# for integration tests in the CI
---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
<% if ENV['CHEF_VERSION'] %>
  chef_version: <%= ENV['CHEF_VERSION'] %>
<% end %>

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true

platforms:
- name: ubuntu-14-04
  driver:
    image: ubuntu:14.04
- name: ubuntu-16-04
  driver:
    image: ubuntu:16.04
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    pid_one_command: /bin/systemd
- name: centos-6
  driver:
    image: centos:6
    intermediate_instructions:
      - RUN yum install -y initscripts
- name: centos-7
  driver:
    image: centos:7
    pid_one_command: /usr/lib/systemd/systemd
- name: oracle-6
  driver:
    image: oraclelinux:6
- name: oracle-7
  driver:
    image: oraclelinux:7
    pid_one_command: /usr/lib/systemd/systemd
- name: debian-7
  driver:
    image: debian:7
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install -y procps
- name: debian-8
  driver:
    image: debian:8
    intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install -y procps
    pid_one_command: /bin/systemd
- name: fedora-26
  driver:
    image: fedora:26
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: fedora-27
  driver:
    image: fedora:27
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
    - RUN dnf install -y yum
- name: opensuse-42
  driver:
    image: opensuse:leap
    pid_one_command: /usr/lib/systemd/systemd
- name: amazonlinux-1
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
- name: amazonlinux-2
  driver:
    image: dokken/amazonlinux-2
    pid_one_command: /usr/lib/systemd/systemd
