---

driver:
  name: vagrant

platforms:
- name: ubuntu-14-04
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16-04
  driver_config:
    box: bento/ubuntu-16.04
- name: centos-6
  driver_config:
    box: bento/centos-6.9
- name: centos-7
  driver_config:
    box: bento/centos-7.4
- name: oracle-6
  driver_config:
    box: bento/oracle-6.9
- name: oracle-7
  driver_config:
    box: bento/oracle-7.3
- name: debian-7
  driver_config:
    box: bento/debian-7.11
- name: debian-8
  driver_config:
    box: bento/debian-8.6
- name: fedora-26
  driver_config:
    box: bento/fedora-26
- name: fedora-27
  driver_config:
    box: bento/fedora-27
- name: opensuse-leap-42
  driver_config:
    box: bento/opensuse-leap-42.1
- name: amazonlinux-1
  driver_config:
    box: realreadme/amazon2016.09
- name: amazonlinux-2
  driver_config:
    box: stakahashi/amazonlinux2

provisioner:
  name: chef_solo
<% if ENV['CHEF_VERSION'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
<% end %>

verifier:
  name: inspec

suites:
- name: default
  run_list:
  - recipe[os-hardening::default]
- name: modules_disabled
  run_list:
  - recipe[os-hardening::default]
  attributes:
    os-hardening:
      security:
        kernel:
          enable_module_loading: false
  verifier:
    inspec_tests:
    - path: test/integration/default
    attributes:
      kernel_modules_disabled: 1
- name: selinux_enabled
  run_list:
  - recipe[os-hardening::default]
  includes:
    - centos-7
  attributes:
    os-hardening:
      security:
        selinux_mode: enforcing
